# Generated by Django 5.1.3 on 2024-12-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
