# Generated by Django 5.1.3 on 2024-12-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_userbook_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='percent_progress',
            field=models.IntegerField(default=0),
        ),
    ]
