# Generated by Django 5.1.3 on 2024-12-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_userbook_last_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
