# Generated by Django 5.1.3 on 2024-12-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0009_alter_book_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="url",
            field=models.URLField(),
        ),
    ]
